HzyUI/Areas/Admin/Controllers/Sys/ChangePwdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Aop;
using ExceptionHandle;
using DbFrame;
using DbFrame.Class;
using Utility;
using BLL;
using Model;
using AppControl.PageCode;

namespace HzyUI.Areas.Admin.Controllers.Sys
{
    public class ChangePwdController : BaseController
    {
        //
        // GET: /ManageSys/ChangePwd/
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            base.MenuID = "Z-150";
        }

        T_Users tuser = new T_Users();

        public override ActionResult Index()
        {
            tuser = db.Find<T_Users>(w => w.uUsers_ID == Tools.getGuid(Tools.getSession("UserID")));
            ViewData["userName"] = tuser.cUsers_Name;
            return View();
        }

        [HttpPost]
        public ActionResult ChangePwd(string oldpwd, string newpwd, string newlypwd)
        {
            if (string.IsNullOrEmpty(oldpwd))
                throw new MessageBox("旧密码不能为空");
            if (string.IsNullOrEmpty(newpwd))
                throw new MessageBox("新密码不能为空");
            if (string.IsNullOrEmpty(newlypwd))
                throw new MessageBox("确认新密码不能为空");
            if (!newpwd.Equals(newlypwd))
                throw new MessageBox("两次密码不一致");
            tuser = db.Find<T_Users>(w => w.uUsers_ID == Tools.getGuid(Tools.getSession("UserID")));
            if (!tuser.cUsers_LoginPwd.Equals(oldpwd.Trim()))//Tools.MD5Encrypt(oldpwd.Trim())))
                throw new MessageBox("旧密码不正确");
            if (!db.Edit<T_Users>(new T_Users() { cUsers_LoginPwd = newlypwd.Trim() }, w => w.uUsers_ID == Tools.getGuid(Tools.getSession("UserID")), li))
                throw new MessageBox(db.ErrorMessge);
            if (!db.Commit(li))
                throw new MessageBox(db.ErrorMessge);
            return Json(new { status = 1 }, JsonRequestBehavior.DenyGet);
        }

    }
}

HzyUI/Areas/Admin/Controllers/Sys/CreateCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Aop;
using ExceptionHandle;
using DbFrame;
using DbFrame.Class;
using Utility;
using BLL;
using Model;
using AppControl.PageCode;

namespace HzyUI.Areas.Admin.Controllers.Sys
{
    public class CreateCodeController : BaseController
    {
        // 根据表 生成 代码
        // GET: /SysManage/CreateCode/
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.MenuID = "Z-160";
        }
        T_CreateCodeBL createcodebl = new T_CreateCodeBL();

        /// <summary>
        /// 获取数据库中所有的表和字段
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetDatabaseAllTable()
        {
            return Json(new { status = 1, value = createcodebl.GetDatabaseAllTable() }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 保存
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(FormCollection fc)
        {
            var Type = fc["ClassType"];
            var Url = (fc["Url"] == null ? Server.MapPath("/Content/CreateFile") : fc["Url"]);
            var Str = fc["Str"];
            var Table = fc["Table"];
            var isall = Tools.getBool(fc["isall"]);
            var template = Server.MapPath("/Content/Template/");

            if (Type == "Model")
            {
                Url = (Url + "\\Model");
                template = template + "Model\\Model.txt";
                Str = string.IsNullOrEmpty(Tools.getString(Str)) ? "M" : Tools.getString(Str);
            }
            else if (Type == "BLL")
            {
                Url = Url + "\\BLL";
                template = template + "Bll\\BLL.txt";
                Str = string.IsNullOrEmpty(Tools.getString(Str)) ? "BL" : Tools.getString(Str);
            }
            else if (Type == "DAL")
            {
                Url = Url + "\\DAL";
                template = template + "DAL\\DAL.txt";
                Str = string.IsNullOrEmpty(Tools.getString(Str)) ? "DA" : Tools.getString(Str);
            }

            if (System.IO.Directory.Exists(Url + "\\"))
            {
                var dir = new System.IO.DirectoryInfo(Url + "\\");
                var fileinfo = dir.GetFileSystemInfos();  //返回目录中所有文件和子目录
                foreach (var i in fileinfo)
                {
                    if (i is System.IO.DirectoryInfo)            //判断是否文件夹
                    {
                        var subdir = new System.IO.DirectoryInfo(i.FullName);
                        subdir.Delete(true);          //删除子目录和文件
                    }
                    else
                    {
                        System.IO.File.Delete(i.FullName);      //删除指定文件
                    }
                }
                //System.IO.Directory.Delete(Url + "\\");
            }
            System.IO.Directory.CreateDirectory(Url);

            if (!System.IO.File.Exists(template))
                throw new MessageBox("模板文件不存在");

            var Content = System.IO.File.ReadAllText(template);

            if (isall)
            {
                var list = createcodebl.GetAllTable();
                foreach (var item in list)
                {
                    Table = item["TABLE_NAME"] == null ? "" : item["TABLE_NAME"].ToString();
                    this.CreateFileLogic(Content, Table, Str, Type, Url);
                }
            }
            else
            {
                if (string.IsNullOrEmpty(Table))
                    throw new MessageBox("请选择表");
                this.CreateFileLogic(Content, Table, Str, Type, Url);
            }

            return Json(new { status = 1 }, JsonRequestBehavior.DenyGet);
        }

        [NonAction]
        public void CreateFileLogic(string Content, string Table, string Str, string Type, string Url)
        {
            var ClassName = Table + Str;

            Content = Content.Replace("<#ClassName#>", ClassName);
            Content = Content.Replace("<#TableName#>", Table);
            string filds = string.Empty;

            if (Type == "Model")
            {
                var col = createcodebl.GetColByTable(Table);
                foreach (var item in col)
                {
                    var key = item["iskey"] == null ? "" : item["iskey"].ToString();
                    var colname = item["colname"] == null ? "" : item["colname"].ToString();
                    var type = item["type"] == null ? "" : item["type"].ToString();

                    switch (type)
                    {
                        case "uniqueidentifier":
                            type = "Guid?";
                            break;
                        case "bit":
                        case "int":
                            type = "int?";
                            break;
                        case "datetime":
                            type = "DateTime?";
                            break;
                        case "float":
                            type = "float?";
                            break;
                        case "money":
                            type = "double?";
                            break;
                        case "decimal":
                            type = "decimal?";
                            break;
                        default:
                            type = "string";
                            break;
                    }

                    if (!string.IsNullOrEmpty(key))
                    {
                        filds += "\t\t[ObjectRemarks.Field(\"" + colname + "\", FieldType = typeof(" + type + "), IsPrimaryKey = true)]" + "\r\n";
                    }
                    else
                    {
                        filds += "\t\t[ObjectRemarks.Field(\"" + colname + "\")]" + "\r\n";
                    }
                    filds += "\t\tpublic " + type + " " + colname + " { get; set; }\r\n\r\n";
                }
                Content = Content.Replace("<#Filds#>", filds);
            }
            System.IO.File.WriteAllText(Url + "\\" + ClassName + ".cs", Content);
        }


    }
}

HzyUI/Areas/Admin/Controllers/Sys/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Aop;
using ExceptionHandle;
using DbFrame;
using DbFrame.Class;
using Utility;
using BLL;
using Model;
using AppControl.PageCode;

namespace HzyUI.Areas.Admin.Controllers.Sys
{
    public class FunctionController : BaseController
    {
        // 功能管理
        // GET: /SysManage/Function/
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.MenuID = "Z-120";
        }

        T_FunctionBL tfbl = new T_FunctionBL();

        #region  查询数据列表
        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override PagingEntity GetPagingEntity(FormCollection fc, int page = 1, int rows = 20)
        {
            //检索
            var query = this.FormCollectionToHashtable(fc);
            //获取列表
            return tfbl.GetDataSource(query, page, rows);
        }
        #endregion  查询数据列表

        #region  基本操作，增删改查
        /// <summary>
        /// 保存
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(T_Function model)
        {
            li = tfbl.Save(model);
            this.KeyID = Tools.getGuidString(model.uFunction_ID);
            if (!db.Commit(li))
                throw new MessageBox(db.ErrorMessge);
            return Json(new { status = 1, ID = KeyID }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Del(string ID)
        {
            if (!db.Commit(tfbl.Delete(ID)))
                throw new MessageBox(db.ErrorMessge);
            return Json(new { status = 1 }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 查询根据ID
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Find(string ID)
        {
            return Json(tfbl.Find(Tools.getGuid(ID)), JsonRequestBehavior.DenyGet);
        }

        #endregion  基本操作，增删改查

    }
}

HzyUI/Areas/Admin/Controllers/Sys/PowerControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzyUI.Areas.Admin.Controllers.Sys
{
    public class PowerControlController : Controller
    {
        //权限控制
        // GET: /ManageSys/PowerControl/

        public ActionResult Index()
        {
            return PartialView();
        }

    }
}

HzyUI/Areas/Admin/Controllers/Sys/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Aop;
using ExceptionHandle;
using DbFrame;
using DbFrame.Class;
using Utility;
using BLL;
using Model;
using AppControl.PageCode;

namespace HzyUI.Areas.Admin.Controllers.Sys
{
    public class RoleController : BaseController
    {
        //角色管理
        // GET: /ManageSys/Role/
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            base.MenuID = "Z-110";
        }

        T_Roles troles = new T_Roles();
        T_RolesBL trolesbl = new T_RolesBL();

        #region  查询数据列表
        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override PagingEntity GetPagingEntity(FormCollection fc, int page = 1, int rows = 20)
        {
            //检索
            var query = this.FormCollectionToHashtable(fc);
            //获取列表
            return trolesbl.GetDataSource(query, page, rows);
        }
        #endregion  查询数据列表

        #region  基本操作，增删改查
        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(T_Roles model)
        {
            li = trolesbl.Save(model);
            this.KeyID = Tools.getGuidString(model.uRoles_ID);
            if (!db.Commit(li))
                throw new MessageBox(db.ErrorMessge);
            return Json(new { status = 1, ID = KeyID }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Del(string ID)
        {
            if (!db.Commit(trolesbl.Delete(ID)))
                throw new MessageBox(db.ErrorMessge);
            return Json(new { status = 1 }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 查询根据ID
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Find(string ID)
        {
            return Json(trolesbl.Find(Tools.getGuid(ID)), JsonRequestBehavior.DenyGet);
        }


        /// <summary>
        /// 获取编号
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Num()
        {
            return Json(new { status = 1, num = Tools.GetOrderNumber(troles.GetTabelName(), Tools.getAttrName(() => troles.cRoles_Number)) });
        }

        #endregion  基本操作，增删改查

    }
}

HzyUI/Areas/Admin/Controllers/Sys/RoleFunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Aop;
using ExceptionHandle;
using DbFrame;
using DbFrame.Class;
using Utility;
using BLL;
using Model;
using AppControl.PageCode;

namespace HzyUI.Areas.Admin.Controllers.Sys
{
    public class RoleFunctionController : BaseController
    {
        // 角色功能
        // GET: /ManageSys/RoleFunction/
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            base.MenuID = "Z-140";
        }

        T_Roles troles = new T_Roles();
        T_Menu tmenu = new T_Menu();
        T_MenuBL tmenubl = new T_MenuBL();
        T_MenuFunction tmenufunction = new T_MenuFunction();
        T_Function tfunction = new T_Function();
        T_RoleMenuFunction trolemenufunction = new T_RoleMenuFunction();

        #region  基本操作，增删改查

        /// <summary>
        /// 获取角色菜单功能
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetRoleMenuFunctionTree(string roleid)
        {
            return Json(new { status = 1, value = tmenubl.GetRoleMenuFunctionTree(roleid) }, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 保存角色功能
        /// </summary>
        /// <param name="json"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(string json, string roleid)
        {
            if (Tools.getGuid(roleid).Equals(Guid.Empty))
                throw new MessageBox("请选择角色");
            var list = ((object[])jss.DeserializeObject(json)).ToList();

            if (!db.Delete<T_RoleMenuFunction>(w => w.uRoleMenuFunction_RoleID == roleid.To_Guid(), li))
                throw new MessageBox(db.ErrorMessge);
            if (list.Count > 0)
            {
                var guid_list = new List<Guid>();
                list.ForEach(item =>
                {
                    var func = (Dictionary<string, object>)item;
                    if (Tools.getString(func["tag"]).Equals("fun"))
                    {
                        if (db.Add<T_RoleMenuFunction>(new T_RoleMenuFunction()
                        {
                            uRoleMenuFunction_MenuID = func["pId"].To_Guid(),
                            uRoleMenuFunction_FunctionID = func["id"].To_Guid(),
                            uRoleMenuFunction_RoleID = roleid.To_Guid()
                        }, li).To_Guid().Equals(Guid.Empty))
                            throw new MessageBox(db.ErrorMessge);
                        guid_list.Add(Tools.getGuid(func["pId"]));
                    }
                });
            }
            if (!db.Commit(li))
                throw new MessageBox(db.ErrorMessge);
            return Json(new { status = 1 }, JsonRequestBehavior.DenyGet);
        }
        #endregion 基本操作，增删改查
    }
}

HzyUI/Areas/Admin/Views/Sys/User/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-content animated fadeInDown">
    <div class="container-fluid">
        <div class="row">
            <!--检索面板-->
            <div class="panel" id="Panel_Search" style="display:none;">
                <div class="panel-body">

                    <form id="form_search" action="javascript:void(0)">
                        <div class="col-sm-3">
                            <h4 class="example-title">用户名</h4>
                            <input type="text" class="form-control" name="cUsers_Name" placeholder="请输入用户名">
                        </div>
                        <div class="col-sm-3">
                            <h4 class="example-title">登录名</h4>
                            <input type="text" class="form-control" name="cUsers_LoginName" placeholder="请输入登录名">
                        </div>
                    </form>


                </div>
                <div class="panel-footer text-right">
                    <button class="btn btn-primary btn-outline" id="btn_search">检索</button>
                </div>
            </div>

            <!--列表面板-->
            <div class="panel">
                <div class="panel-heading">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-outline" onclick="location=location"><i class="fa fa-refresh"></i>&nbsp;刷新</button>
                        <button type="button" class="btn btn-default btn-outline" onclick="ShowSearch(this)" data-power="Search"><i class="fa fa-chevron-down"></i>&nbsp;检索</button>
                        <button type="button" class="btn btn-default btn-outline" onclick="Func.OpenInfoPage('add')" data-power="Add"><i class="fa fa-plus"></i>&nbsp;添加</button>
                        <button type="button" class="btn btn-default btn-outline" onclick="Func.OpenInfoPage('edit')" data-power="Edit" disabled="disabled"><i class="fa fa-pencil"></i>&nbsp;修改</button>
                        <button type="button" class="btn btn-default btn-outline" onclick="$List.Del({url:'@Url.Action("Del")'});" data-power="Del" disabled="disabled"><i class="fa fa-trash"></i>&nbsp;删除</button>
                        <a class="btn btn-default btn-outline" onclick="$List.ExportExcel('@Url.Action("ExportExcel")')" id="Btn_Power_GetExcel"><i class="fa fa-file-excel-o"></i>&nbsp;导出 Excel</a>
                    </div>

                </div>
                <div class="panel-body text-center">
                    <table id="btable"></table>
                </div>
            </div>

        </div>

    </div>
</div>
@section css{

}
@section js{
    <script src="~/Resource/FrameWork/js/FrameWork_List.js"></script>
    <script type="text/javascript">
        var area = "@(ViewContext.RouteData.DataTokens["area"])";
        var controller = "@(ViewContext.RouteData.Values["controller"])";
        var action = "@(ViewContext.RouteData.Values["action"])";
        var FormID = "Form_" + area + controller + action;
        var thisWindowName = "FrameWork_" + area + controller + action;
        $(function () {
            Func.TableInit();
        });

        var Func = {
            TableInit: function () {
                $List.BTable({
                    url: "@Url.Action("GetDataSource")",
                    columns: JSON.parse('@Html.Raw(ViewBag.ColModel)'),
                });
            },
            OpenInfoPage: function (tag) {
                $.ModalOpen({
                    id: FormID,
                    parentIframeName: thisWindowName,
                    url: "@Url.Action("Info")" + (tag == "add" ? "" : "/?ID=" + $KeyValue[0]._ukid),
                    width: "500px",
                    height: "500px",
                    btn: false,
                });
            }
        };
    </script>
}

HzyUI/Areas/Admin/Views/Sys/User/Info.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-content animated fadeInDown">
    <div class="container-fluid">
        <div class="row" id="form">
            <!--检索面板-->

            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">用户名</h4>
                <input type="text" class="form-control" name="cUsers_Name" data-bind="value:cUsers_Name" placeholder="请输入用户名" />
            </div>

            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">登录名</h4>
                <input type="text" class="form-control" name="cUsers_LoginName" data-bind="value:cUsers_LoginName" placeholder="请输入登录名" />
            </div>

            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">登录密码</h4>
                <input type="text" class="form-control" name="cUsers_LoginPwd" data-bind="value:cUsers_LoginPwd" placeholder="请输入登录密码" />
            </div>

            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">邮箱地址</h4>
                <input type="text" class="form-control" name="cUsers_Email" data-bind="value:cUsers_Email" placeholder="请输入邮件" />
            </div>

            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">角色</h4>
                @WebHtml.FindBackControl(new
                       {
                           Text = "cRoles_Name",
                           ID = "uRoles_ID",
                           Placeholder = "请选择角色",
                           FindClick = @"$.FindBack.OpenPage({
                                    title: '请选择角色',
                                    content: '" + Url.Action("Index", "Role", new { fun = "findback" }) + @"',
                                    callBack:function(id){ Func.FindBack.CallBack(id,'Role') }
                                });",
                           RemoveClick = "Func.FindBack.CallBack(null,'Role');"
                       })
            </div>


        </div>

    </div>
</div>
<!--按钮-->
<div style="height:100px; width:100%;"></div>
<div class="my-ButtonBar text-right">
    <div class="btn-group">
        <button type="button" class="btn btn-success btn-outline" data-bind="visible:!Func.IsAdd()" onclick="$Form.ResetUrl(null)">新增</button>
        <button class="btn btn-primary btn-outline" onclick="Func.Save()">提交</button>
        <button class="btn btn-danger btn-outline" onclick="Lay.close($.GetFrameIndex())">关闭</button>
    </div>
</div>
@section css{
}
@section js{
    <script src="~/Resource/FrameWork/js/FrameWork_Form.js"></script>
    <script type="text/javascript">
        var KeyId = FW.GetQueryString("ID");
        model = new vModel();
        $(function () {
            ko.applyBindings(model);//注册vModel
            Func.Load(KeyId);
            //Func.Select_Roles();
        });

        var Func = {
            IsAdd: function () {
                if (KeyId == null || KeyId == "" || KeyId == undefined || KeyId == "@Guid.Empty")
                    return true;
                return false;
            },
            Load: function (ID) {
                $Form.Load({
                    id: ID,
                    url: "@Url.Action("Find")",
                    callBack: function (r) {
                    }
                });
            },
            Save: function () {
                $Form.Save({ url: "@Url.Action("Save")", isClose: true });
            },
            FindBack: {
                CallBack: function (row, tag) {
                    console.log(row);
                    if (tag == "Role") {
                        model.uRoles_ID((row ? row._ukid : ""));
                        model.cRoles_Name((row ? row.cRoles_Name : ""));
                    }

                }
            },
        };

        function vModel() {
            this.uUsers_ID = ko.observable("");
            this.cUsers_Name = ko.observable("");
            this.cUsers_LoginName = ko.observable("");
            this.cUsers_LoginPwd = ko.observable("");
            this.uRoles_ID = ko.observable("");
            this.cUsers_Email = ko.observable("");
            this.cRoles_Name = ko.observable("");
        }
    </script>
}